### PR TITLE
Update `develop` branch to match `master`

### PR DESCRIPTION
**Pull request by ashelkovnykov**
This is a one-time thing that needs to be done to make `develop` the primary development branch.

### CODE REVIEW

**Comment by brbenji** [comment]
is there more to this PR than the 4 commits?
I'm not clear on how this is a one time thing.

**Comment by ashelkovnykov** [comment]
@brbenji 
The normal workflow should be:
1. Developers PR completed work on top of `develop`
2. New version releases `git cherry-pick` commits from `develop` to apply to `master` in a PR

Therefore, committing from `master` to `develop` never happens, since `develop` is always either ahead of `master` (in some way; it has some commit `master` doesn't) or identical to `master`.

However, in this PR, I'm attempting to merge from `master` to `develop`, because we haven't instituted this workflow yet. This should be the only time we ever need to move commits from `master` to `develop`, instead of the other way around.

**Review by bonbud-macryg — APPROVED** [review]
@ashelkovnykov Your comment above clarifies things somewhat; I wasn't sure why these commits were in here but comparing branches I see what you're doing. LGTM.

**Review by brbenji — APPROVED** [review]
LGTM

**Comment by rovmug-ticfyn** [comment]
LGTM

**Pull request merged**
